Update mcr.cpp
redevilable/Course-Project-SE-United pull request #3
Opened 2023-09-11 13:13 UTC by redevilable

2023-09-11 13:20 UTC, StephenWang3 approved these changes
LGTM

2023-09-11 15:40 UTC, Salvatores71 commented
isWin() 算法可简化，判断是否为‘x’或'o'是无意义的

2023-09-11 15:42 UTC, Salvatores71 requested changes
用户输入表格位置需要判断是否超出范围，若是需要提示并要求重新输入直到为正确数据。

2023-09-12 05:01 UTC, EricHo233 approved these changes

2023-09-12 05:01 UTC, merged